//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group01_QuanLyLuanVan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeTai
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeTai()
        {
            this.DanhGias = new HashSet<DanhGia>();
            this.ThongBaos = new HashSet<ThongBao>();
            this.TienDoes = new HashSet<TienDo>();
            this.YeuCaus = new HashSet<YeuCau>();
        }

        public DeTai(int diem)
        {
            this.diem = diem;
        }
        public DeTai(string tenDeTai, string moTa, string yeuCauChung, DateTime ngayBatDau, DateTime ngayKetThuc, int nhomId, string hoTen, string tenTheLoai)
        {
            this.tenDeTai = tenDeTai;
            this.moTa = moTa;
            this.yeuCauChung = yeuCauChung;
            this.ngayBatDau = ngayBatDau;
            this.ngayKetThuc = ngayKetThuc;
            this.nhomId = nhomId;
            this.hoTen = hoTen;
            this.tenTheLoai = tenTheLoai;
        }
        public DeTai(string deTaiId, string tenDeTai, string tenTheLoai, string moTa, string yeuCauChung,
    DateTime ngayBatDau, DateTime ngayKetThuc, int soLuong, int trangThai)
        {
            this.deTaiId = deTaiId;
            this.tenDeTai = tenDeTai;
            this.TheLoai.tenTheLoai = tenTheLoai;
            this.moTa = moTa;
            this.yeuCauChung = yeuCauChung;
            this.ngayBatDau = ngayBatDau;
            this.ngayKetThuc = ngayKetThuc;
            this.soLuong = soLuong;
            this.trangThai = trangThai;
        }

        public DeTai(string deTaiId, string tenDeTai, string tenTheLoai, string hoTen, string moTa, string yeuCauChung,
            DateTime ngayBatDau, DateTime ngayKetThuc, int soLuong, string tenTrangThai)
        {
            this.deTaiId = deTaiId;
            this.tenDeTai = tenDeTai;
            this.hoTen = hoTen;
            this.tenTheLoai = tenTheLoai;
            this.moTa = moTa;
            this.yeuCauChung = yeuCauChung;
            this.ngayBatDau = ngayBatDau;
            this.ngayKetThuc = ngayKetThuc;
            this.soLuong = soLuong;
            this.tenTrangThai = tenTrangThai;
        }
        public DeTai(string deTaiId, string tenDeTai, string tenTheLoai, string moTa, string yeuCauChung,
    DateTime ngayBatDau, DateTime ngayKetThuc, int soLuong, string tenTrangThai)
        {
            this.deTaiId = deTaiId;
            this.tenDeTai = tenDeTai;
            this.tenTheLoai = tenTheLoai;
            this.moTa = moTa;
            this.yeuCauChung = yeuCauChung;
            this.ngayBatDau = ngayBatDau;
            this.ngayKetThuc = ngayKetThuc;
            this.soLuong = soLuong;
            this.tenTrangThai = tenTrangThai;
        }

        public DeTai(string deTaiId, string tenDeTai, string tenTheLoai, string tenNhom)
        {
            this.deTaiId = deTaiId;
            this.tenDeTai = tenDeTai;
            this.tenTheLoai = tenTheLoai;
            this.tenNhom = tenNhom;
        }

        public DeTai(string deTaiId, string tenDeTai, string tenTheLoai, string tenNhom, string phanTram)
        {
            this.deTaiId = deTaiId;
            this.tenDeTai = tenDeTai;
            this.tenTheLoai = tenTheLoai;
            this.tenNhom = tenNhom;
            this.phanTram = phanTram;
        }

        public int id { get; set; }
        public string deTaiId { get; set; }
        public string tenDeTai { get; set; }
        public string moTa { get; set; }
        public string yeuCauChung { get; set; }
        public string tenTheLoai { get; set; }
        public string tenTrangThai { get; set; }
        public string tenNhom { get; set; }

        public string phanTram { get; set; }
        public string hoTen { get; set; }


        public Nullable<int> soLuong { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<System.DateTime> ngayBatDau { get; set; }
        public Nullable<System.DateTime> ngayKetThuc { get; set; }
        public string theLoaiId { get; set; }
        public Nullable<int> nhomId { get; set; }
        public Nullable<int> an { get; set; }
        public Nullable<double> diem { get; set; }
        public string giangVienId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual Nhom Nhom { get; set; }
        public virtual TheLoai TheLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongBao> ThongBaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TienDo> TienDoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuCau> YeuCaus { get; set; }
    }
}
