//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group01_QuanLyLuanVan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBao
    {
        public int thongBaoId { get; set; }
        public string tieude { get; set; }
        public string noiDung { get; set; }
        public string deTaiId { get; set; }
        public Nullable<System.DateTime> ngay { get; set; }
        public Nullable<int> trangthai { get; set; }
    
        public virtual DeTai DeTai { get; set; }
    }
}
