//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group01_QuanLyLuanVan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhanYeuCau
    {
        public TinNhanYeuCau() { }
        public TinNhanYeuCau(int tinNhanId, string tinNhan, DateTime thoiGian, string username, int yeuCauId, string avatar)
        {
            this.tinNhanId = tinNhanId;
            this.tinNhan = tinNhan;
            this.thoiGian = thoiGian;
            this.username = username;
            this.yeuCauId = yeuCauId;
            this.avatar = avatar;

        }

        public TinNhanYeuCau(int tinNhanId, string tinNhan, DateTime thoiGian, string username, int yeuCauId)
        {
            this.tinNhanId = tinNhanId;
            this.tinNhan = tinNhan;
            this.thoiGian = thoiGian;
            this.username = username;
            this.yeuCauId = yeuCauId;
        }

        public TinNhanYeuCau(string username, string uid)
        {
            this.username = username;
            this.uid = uid;
        }
        public string avatar { get; set; }
        public string uid { get; set; }



        public int tinNhanId { get; set; }
        public string tinNhan { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public string username { get; set; }
        public Nullable<int> yeuCauId { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual YeuCau YeuCau { get; set; }
    }
}
