//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group01_QuanLyLuanVan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TinNhanYeuCau
    {
        public int tinNhanId { get; set; }
        public string tinNhan { get; set; }
        public Nullable<System.DateTime> thoiGian { get; set; }
        public string username { get; set; }
        public Nullable<int> yeuCauId { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual YeuCau YeuCau { get; set; }
    }
}
