//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group01_QuanLyLuanVan.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YeuCau()
        {
            this.TinNhanYeuCaus = new HashSet<TinNhanYeuCau>();
        }
    
        public int yeuCauId { get; set; }
        public string noiDung { get; set; }
        public Nullable<int> trangThai { get; set; }
        public Nullable<int> phanTram { get; set; }
        public string deTaiId { get; set; }
    
        public virtual DeTai DeTai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TinNhanYeuCau> TinNhanYeuCaus { get; set; }
    }
}
